### ISSUE TITLE
'Action Points' tracking

### ISSUE THREAD

**Issue by krbz999** [krbz999/artichron#24]
Action Points, or pips, are a resource used to track the actions of a combatant during combat.

The points have the following properties:
- [x] Moving 5m costs 1 pip.
- [x] An attack with a weapon wielded in one hand costs 1 pip.
- [x] Casting a spell or using a two-handed weapon costs 2 pips.
- [x] At the end of the round, unspent pips lower the critical threshold of the initiative roll (1d12x).
- [x] Initiative is rerolled at the start of each round, which uses pips.
- [x] Fusing an item onto another item costs 1 pip.
- [x] Using an elixir to gain a buff costs 1 pip.
- [x] Using a restorative elixir costs 1 pip.
- [x] The cost of 1-2 pips for using an arsenal item (weapon, shield, spell) are suggested defaults, and the items should have a property (`system.cost.value`?) where this can be adjusted.
- [x] Blocking or parrying when receiving damage costs 1 pip per item used to defend.
- [x] At the end of a combatant's turn an amount of unspent pips equal to no more than the size of their Stamina or Mana pool (whichever is highest) are carried over to their next turn.
- [x] Pips are restored at the start of each round; a combatant gains a number of pips equal to the size of their health dice pool. This is added onto however many pips they had left over.
- [x] When a combatant is created, they have a number of pips equal to the maximum size of their health pool plus the maximum size of their stamina or mana pool (whichever is highest).

TODO:
- [x] How are pips restored or increased?
- [x] How much does a combatant start with? And when (every round, start of combat)?
- [x] What happens to pips that are not spent at the end of the combatant's turn?

### Update
We have agreed that combatants do *not* retain a maximum amount of pips when their turn ends; instead they retain all action points.

All action points are lost (and spent to determine the initiative order of the next round) once the round ends.

All combatants gain a set number of action points at the start of the round, and with additional points for each turn they have in the round. (For example: You start with 6 points but have 5 turns, so you get an additional +10 points for a total of 16.)

- [x] Remove the turn-end update on combatants' action points.
- [x] Tie action points to the actor rather than the combatant.
- [x] Use multiple combatants rather than mutating the `Combat#turns` property.
- [x] Recalculate the number of starting action points at the top of each round.

**Comment by Mythacri** [comment]
All the actions for spending pips seem to be fine. I like the addition of unused pips lowering the crit threshold instead of carrying over to the next round.

Fusing an item as by spending a pip seems okay but are players going to be fusing items in the middle of combat?

TODO:
Pips are restored naturally at the start of each round. A player regains a number of pips equal to their maximum pool of health dice.

I would suggest a combatant starts with a number of pips equal to their health dice + their stamina dice or mana dice, whichever is higher. This way a player's maximum number of pips increases as they become stronger.

At the end of a combatant's turn an amount of unspent pips equal to the number of their maximum stamina dice or mana dice are carried over to their next turn. The goal here is similar to the one above where the player's abilities grow naturally over time.

Please advise if this sounds good. If not, I can also come up with a pip system where the pips are their own values and are not tied to the characters abilities at all.

**Comment by krbz999** [comment]
I'll give my thoughts on each of the suggestions individually.

> Pips are restored naturally at the start of each round. A player regains a number of pips equal to their maximum pool of health dice.

Why health?
Also 'regain' implies to me that there is a maximum. I am wondering if there should be. 
We could also involve a dice roll here somehow.

> I would suggest a combatant starts with a number of pips equal to their health dice + their stamina dice or mana dice, whichever is higher. This way a player's maximum number of pips increases as they become stronger.

I get that health dice need a bit more involvement, but I'm not sure I see the logic behind tying pips to them. Agree that the starting amount should be something static however.

> At the end of a combatant's turn an amount of unspent pips equal to the number of their maximum stamina dice or mana dice are carried over to their next turn. The goal here is similar to the one above where the player's abilities grow naturally over time.

This part sounds good to limit the pips so it doesn't grow insanely. It might still since a combatant can get many turns in a round, but that's an issue for later.

**Comment by krbz999** [comment]
We have agreed that combatants do *not* retain a maximum amount of pips when their turn ends; instead they retain all action points.

All action points are lost (and spent to determine the initiative order of the next round) once the round ends.

All combatants gain the same number of action points at the start of the round, but with additional points for each turn they have in the round. (For example: You start with 6 points but have 5 turns, so you get an additional +10 points.)
