### ISSUE TITLE
"Carousel" combat tracker

### ISSUE THREAD

**Issue by krbz999** [krbz999/artichron#28]
A horizontal combat tracker that shows combatants in a different format than the standard one.

This should always be pinned at the top, just below the scene navigation, when a Combat is active.

### Needs
- [x] Show each combatant in the current initiative order.
- [x] Show the status conditions that affect the combatants.
- [x] Show an image of the combatant (token image).
- [x] Show the current amount of action points of a combatant.
- [x] Highlight the current combatant.
- [x] When combat is updated, re-render the custom tracker.
- [x] When combat is ended, minimize and hide the custom tracker.
- [x] Allow for toggling a combatant as defeated.
- [x] Allow for toggling a combatant's `hidden` state.
- [x] Allow for pinging the location of a combatant.
- [x] Allow for rendering a context menu upon right-clicking a combatant.
- [x] Apply visual overlay on defeated combatants.
- [x] Implement scrolling behavior when the carousel goes out of bounds.
- [x] If a combatant has 15 pips or more, just show one dot followed by "(n)".

### Nice to Have
- [x] Slide animations when the combat order changes, animating the movement of the combatants to their new positions.
- [x] Allow for adjusting the action points directly in the tracker without opening the Combatant sheet.
- [x] Show a display of a combatant's health (vertical or horizontal health bar).
