### ISSUE TITLE
Fusion iteration

### ISSUE THREAD

**Issue by krbz999** [krbz999/artichron#42]
Add some general rules for how item A is fused onto item B.
- [ ] If both items are the same item type, generally their properties are combined (sets and arrays), added together (numbers), or the highest value is picked (such as for one- or two-handed).
- [x] Implement a 'reach' property for items (a numeric value), since it doesn't make sense to combine the range of items together, but that does make sense for a 'reach' value. Alternatively, add an 'Extended Reach' attribute (boolean value), which describes whether the range values are combined when fusing or not.
- [x] Add a 'max' property on items that describe how many fusions an item  can have on it.

### Specific Properties: all item types
- [x] Attributes: This set is merged together.
- [x] Subtype: This is ignored.
- [x] Price: This is summed together.
- [x] Weight: This is summed together.
- [ ] If item A has any enhancements, these are added to the fusion effect onto item B.
- [ ] If item A grants any buffs to the owning actor, these are IGNORED and NOT added to item B.

### Specific Properties: Arsenal
- [x] Wielding: The highest value is used (one- or two-handed).
- [x] Range, reach, action cost: These values are ignored as they live on activities.
- [x] Armor Value (shields): This value is halved before being added to item B, but ignored entirely if item B is not a shield.
- [x] Damage Bonuses: These are all summed together.
- [ ] If both item A and item B are buff spells, buffs added by item A are added to item B's pool of available buffs.

### Activities
- [x] Damage activity: Unless the target item is a spell, this is ignored.
- [x] Defend activity: Unless the target item is a weapon or shield, this is ignored.
- [x] Effect activity: Ignored.
- [x] Healing activity: Ignored.
- [x] Teleport activity: Unless the target item is a spell, this is ignored.

### Specific Properties: Armor
- [x] Amor Value: This value is halved before being added to item B.
- [x] Resistances: These are all summed together.

### Edge cases
- [x] Add 'transferrable' property to item attributes to describe whether they are automatically added to fusion effects. (For example, 'ammunition' makes no sense.)

**Comment by Mythacri** [comment]
Okay, I like this a lot. The one point of confusion I have is combining weapons with spells. Mostly on the basis of what this looks like? It appears that is only goes one way though, implying spells can be more or less "infused" onto weapons? Am I understanding this correctly? If so, I would like to clarify whether it is the base damage value of the spell OR if it is whatever the immediate damage value of the spell is

**Comment by krbz999** [comment]
> If so, I would like to clarify whether it is the base damage value of the spell OR if it is whatever the immediate damage value of the spell is

A weapon can be fused onto a spell, and a spell can be fused onto a weapon, both ways are possible.

When fusing a spell onto a weapon:
> If Item A is a spell, and item B is a weapon, item B gains one damage formula of item A, but halved.

You would have to choose at the time.

**Comment by krbz999** [comment]
Rather than sometimes halving some things, I think for simplicity's sake it would be good to always halve all stuff from the item being fused onto another.

**Comment by krbz999** [comment]
This entire subsystem should be redone with removal of weapons and shields.

- [ ] Spells can be fused onto armor.
- [ ] Armor items can be fused together?

**Comment by krbz999** [comment]
Spells are magical objects that can be used in a variety of ways or fused onto a piece of equipment. These magical objects all have a quality, a rating between 1 and 5, and are all of one of three origins; planar, elemental, or technological.

When fusing a spell onto armor, the rules are as follows:
- Half the value of the spell is added to the armor. If a spell is worth 50, the value of the armor is increased by 25.
- If the spell is of elemental origin, the armor's elemental defenses are each boosted by an amount equal to the spell's quality.
- If the spell is of planar origin, the armor's physical defense is boosted by an amount equal to two times the spell's quality.
- If the spell is of technological origin, the armor now allows its wearer to roll more skill dice equal to the quality of the spell.
