### ISSUE TITLE
Combat hazards

### ISSUE THREAD

**Issue by krbz999** [krbz999/artichron#51]
Proposed ideas for features that encompass a hazard on the map:
- [ ] Creating a wall; an area that blocks line of sight in and out. (Unsure how to implement, might need regions or templates or WallDocuments).
- [ ] Difficult terrain. An area that reduces movement speed. (Possibly created via MeasuredTemplates which a hook or socket turn into a Region.)
- [ ] Damage-over-time areas. A scene region that causes damage when moving through it.
- [ ] Towers. A structure at a point that deals damage to creatures every round within a certain radius. (Auras?)

**Comment by krbz999** [comment]
Difficult terrain is a core region behavior (sort of). This should be relied on. Just have to configure movement types.
