### ISSUE TITLE
Skills and Clocks

### ISSUE THREAD

**Issue by krbz999** [krbz999/artichron#84]
_(New discussion. Succeeds #35.)_

# Implementation:
- [x] There is a defined list of skills: Agility, Brawn, Mind, Spirit.
- [x] When rolling a "skill check," the user picks two skills that fit, or the same skill twice.
- [x] Each skill has a number of dice (initially 2) as well as a number of guaranteed hits (initially 0).
- [x] The combined skill roll adds up the dice and the guaranteed hits and rolls all together. Each die is a d6.
- [x] Every 6 rolled is a hit.
- [x] The GM determines what the threshold is for success. (At initial levels, this is likely just going to be 1.)
- [x] A party actor shows clocks, and the GM determines which clock goes up by one when the roll is performed depending on whether it was a success or not. (See: #86.)
- [x] Generally the attempt succeeds regardless in some fashion, but the success or failure might optionally result in a better or worse outcome immediately. If a clock gets filled, it will result in a consequence for the next session / next dungeon / etc.
- [x] Create a roll table of generic detriments or boons that a GM can use in case no story-related consequences apply.

**Comment by Mythacri** [comment]
Here's a first crack at some boons on a d6 table

Boons:
1 - Your success thus far have bolstered your confidence! For the next session, you have one additional Action Point during your first turn of each combat.

2 - You have managed to do exceptional well today and are more comfortable with your abilities. The first time the detriment clock would increase for you next session, it does not.

3 - The exceptional ways in which you accomplished your goals today  have taught you many valuable things. The first time you roll for Mind or for Spirit next session, you add two extra dice to the pool.

4 - Having easily made your way through today's hardships, you are more than well rested for the next session! Your maximum hit points are increased by 20 for the next session.

5 - The training you've put yourself under recently has paid off! During the next session, your Brawn and Agility rolls explode!

6 - The strongest weapons are forged in the toughest environments and your body is no exception! For the next session, you re-roll any 1's in your damage dice.

**Comment by Mythacri** [comment]
Here's a first crack at some detriments on a d6 table

Detriments:
1 - Your core is shaken due to your injuries today. You have 1 fewer health dice next session.

2 - Injuries from your adventures today have made it hard for you to rest properly. You have 1 fewer Action Point during the first round of each combat next session.

3 - You can't help but feel that some greater being is disappointed in your success and failures after today.  You roll 1 fewer dice any time you roll Spirit during the next session.

4 - Ambient magic has seeped into your weary body. You take 1d6 additional damage when subjected to lightning, fire, ice, or wind magic.

5 - Your body is weak and tired after the strain you've put on it today. Whenever you roll for Agility or Brawn during next session you roll 1 fewer dice.

6 - You have pushed your body to its limits today and have severely overexerted yourself. You have 1 fewer mand and 1 fewer stamina dice next session.
